# Generated by Django 4.1.1 on 2022-11-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='quiries',
            new_name='msg',
        ),
    ]
