# Generated by Django 4.1.1 on 2022-11-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_contact_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='msg',
            field=models.CharField(max_length=200),
        ),
    ]
