# Generated by Django 4.1.1 on 2022-11-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_contact_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='msg',
            new_name='description',
        ),
    ]
