# Generated by Django 4.1.1 on 2022-11-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_application'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='loanRequest',
        ),
    ]
